#!/bin/bash
# Réaliser un script qui permet de surveiller les modifications du fichier /etc/crontab
# et envoie un mail à root si celui-ci a été modifié. Créez une tache plannifiée pour
# script tous les jours à minuit.

echo '#!/bin/bash' > mon_script.sh
echo 'md5sum /etc/crontab > watch_crontab' > mon_script.sh